#!/bin/bash
#bspc monitor -d    ﳁ   ﭮ  
#bspc monitor -d TERM WEB CODE MISC EDIT CHAT DISCORD MUSIC
bspc monitor -d   ﬏    ﭮ 
#for i in $(bspc query -D --names)
#do
    #bsp-layout set tall $i -- --master-size 0.65 &
#done

bspc config window_gap          0
bspc config split_ratio          0.6
bspc config border_width         2
bspc config top_padding 28
bspc config focused_border_color "#a89984"
bspc config normal_border_color "#282828"

bspc config borderless_monocle true
bspc config single_monocle true
bspc config gapless_monocle false
